// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://arcgis-playground-api.onrender.com' | (string & {})
}

/**
 * GeometryCreate
 */
export type GeometryCreate = {
  /**
   * Label
   */
  label?: string | null
  /**
   * Wkt
   */
  wkt: string
}

/**
 * GeometryRead
 */
export type GeometryRead = {
  /**
   * Label
   */
  label?: string | null
  /**
   * Wkt
   */
  wkt: string
  /**
   * Id
   */
  id: number
}

/**
 * GeometryUpdate
 */
export type GeometryUpdate = {
  /**
   * Label
   */
  label?: string | null
  /**
   * Wkt
   */
  wkt?: string | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

export type ListGeometriesGeometryGetData = {
  body?: never
  path?: never
  query?: never
  url: '/geometry/'
}

export type ListGeometriesGeometryGetResponses = {
  /**
   * Response List Geometries Geometry  Get
   *
   * Successful Response
   */
  200: Array<GeometryRead>
}

export type ListGeometriesGeometryGetResponse =
  ListGeometriesGeometryGetResponses[keyof ListGeometriesGeometryGetResponses]

export type CreateGeometryGeometryPostData = {
  body: GeometryCreate
  path?: never
  query?: never
  url: '/geometry/'
}

export type CreateGeometryGeometryPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateGeometryGeometryPostError =
  CreateGeometryGeometryPostErrors[keyof CreateGeometryGeometryPostErrors]

export type CreateGeometryGeometryPostResponses = {
  /**
   * Successful Response
   */
  200: GeometryRead
}

export type CreateGeometryGeometryPostResponse =
  CreateGeometryGeometryPostResponses[keyof CreateGeometryGeometryPostResponses]

export type DeleteGeometryGeometryGeomIdDeleteData = {
  body?: never
  path: {
    /**
     * Geom Id
     */
    geom_id: number
  }
  query?: never
  url: '/geometry/{geom_id}'
}

export type DeleteGeometryGeometryGeomIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteGeometryGeometryGeomIdDeleteError =
  DeleteGeometryGeometryGeomIdDeleteErrors[keyof DeleteGeometryGeometryGeomIdDeleteErrors]

export type DeleteGeometryGeometryGeomIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetGeometryGeometryGeomIdGetData = {
  body?: never
  path: {
    /**
     * Geom Id
     */
    geom_id: number
  }
  query?: never
  url: '/geometry/{geom_id}'
}

export type GetGeometryGeometryGeomIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetGeometryGeometryGeomIdGetError =
  GetGeometryGeometryGeomIdGetErrors[keyof GetGeometryGeometryGeomIdGetErrors]

export type GetGeometryGeometryGeomIdGetResponses = {
  /**
   * Successful Response
   */
  200: GeometryRead
}

export type GetGeometryGeometryGeomIdGetResponse =
  GetGeometryGeometryGeomIdGetResponses[keyof GetGeometryGeometryGeomIdGetResponses]

export type UpdateGeometryGeometryGeomIdPutData = {
  body: GeometryUpdate
  path: {
    /**
     * Geom Id
     */
    geom_id: number
  }
  query?: never
  url: '/geometry/{geom_id}'
}

export type UpdateGeometryGeometryGeomIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateGeometryGeometryGeomIdPutError =
  UpdateGeometryGeometryGeomIdPutErrors[keyof UpdateGeometryGeometryGeomIdPutErrors]

export type UpdateGeometryGeometryGeomIdPutResponses = {
  /**
   * Successful Response
   */
  200: GeometryRead
}

export type UpdateGeometryGeometryGeomIdPutResponse =
  UpdateGeometryGeometryGeomIdPutResponses[keyof UpdateGeometryGeometryGeomIdPutResponses]

export type RootGetData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}
